version: "3.5"

services:
  database:
    image: postgres:latest
    container_name: database
    restart: always
    environment:
      - POSTGRES_USER=payment_risk
      - POSTGRES_PASSWORD=payment_risk123
    ports:
      - 5432:5432
    volumes:
      - database:/var/lib/postgresql/data

volumes:
  database:
    driver: local
