default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  host: localhost
  username: <%= ENV['DATABASE_USERNAME'] %> 
  password: <%= ENV['DATABASE_PASSWORD'] %> 

development:
  <<: *default
  database: payment_risk_gateway_development

test:
  <<: *default
  database: payment_risk_gateway_test

production:
  <<: *default
  database: payment_risk_gateway_production
  username: payment_risk_gateway
  password: <%= ENV["PAYMENT_RISK_GATEWAY_DATABASE_PASSWORD"] %>
